# Generated by Django 4.0.6 on 2022-08-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_university_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
